export const inspectionPrompt =
  'Inspect the task and environment before making changes.\n\n' +
  'Original task:\n{{input.question}}\n\n' +
  'Treat the original task as the only source of truth. In this phase, preserve what the task actually requires; do not rewrite it into a preferred solution route, a narrower subproblem, or a safer generalized version.\n\n' +
  "Your goal in this phase is to build the handoff model for working, not to solve or implement the task. Use available read-only tools to understand what needs to be delivered, what files or commands matter, and what constraints are visible. Keep a running checklist for the final handoff draft: intent, subgoals, and each subgoal item's name, type, description, relevant_files, and handoff.confirmed / handoff.candidates / handoff.risks. Stop using tools once this checklist is sufficient for working to preserve, do, test, or investigate the right things.\n\n" +
  'Do not edit files, run mutation commands, or implement the solution in this phase.\n\n' +
  'The final handoff draft must use field labels and meanings that match the extraction schema. A later schema extraction step will convert the draft into strict JSON, so make the draft easy to map directly and do not invent extra field names.\n\n' +
  'In intent, write a short stable statement of the task goal. Do not include commands, validation steps, or implementation detail in intent.\n\n' +
  'In subgoals, write a short list of structured handoff items anchored to authoritative task facts and confirmed read-only evidence. Do not broaden the task scope. Before writing subgoals, identify the authoritative facts from the original task and confirmed read-only evidence. Organize subgoals around those facts; do not replace them with a broader, safer, or more generic version of the task. Each item must include name, type, description, relevant_files, and handoff.\n\n' +
  'Keep task-required boundaries explicit. Preserve exact deliverables, paths, filenames, ports, interfaces, dataset or taxonomy scope, allowed-edit regions, untouched-file constraints, and no-extra-artifact constraints when the original task makes them part of the contract. Do not silently narrow, broaden, rename, or reinterpret those boundaries.\n\n' +
  'If the task still supports multiple plausible contract interpretations after read-only inspection, keep that ambiguity explicit as unresolved contract uncertainty. Do not promote one plausible interpretation to fact unless source_of_truth or confirmed evidence resolves it.\n\n' +
  'Do not present a candidate route, guessed exploit, tentative parser strategy, possible bypass, or untested implementation path as a confirmed fact. If inspection has not directly established it, keep it tentative.\n\n' +
  'Do not write a chosen implementation recipe, algorithm shape, exploit path, parser design, compiler trick, framework choice, or runtime workaround as though the task contract requires it unless source_of_truth explicitly requires that exact route. Candidate routes belong in tentative language only.\n\n' +
  'Do not put candidate-route content into description for a delivery_contract. description is only for the required result, confirmed facts, and exact boundary constraints. It is not for "leading candidate", "use X", "write Y algorithm", guessed exploit paths, parser strategy, compiler trick, or runtime workaround unless source_of_truth explicitly requires that exact route.\n\n' +
  'A subgoal is a typed goal, constraint, target, or unknown; it is not an execution step or action list. Do not classify subgoals by what command the next phase might run. Classify them by the role they play in the handoff model: final contract, flexible exploration goal, measurable target, or working-only unknown.\n\n' +
  'Use type delivery_contract for the final delivery checks and acceptance surface, not for the next action that may implement them. A delivery_contract answers: "What immutable fact must be true when the final solution is handed over or tested?"\n' +
  'For delivery_contract, preserve immutable verifier-facing details exactly: literal paths, hostnames, ports, RPC or API names, CLI arguments, output files, schema fields, known contaminated scope, placeholder rules, service lifetime, background process expectations, observable behavior, numeric representation, units, precision, and required call ordering. Behavioral protocols are contracts too: argument meanings, call sequence, persistence, waiting, side effects, and error-visible output belong here when tests observe them. If a verifier-facing file must be produced but its contents depend on data inference, training, optimization, sampling, cracking, search, or runtime experiments, keep only the file path, format, schema, row count, and acceptance surface as delivery_contract; classify the content-generation objective as exploration_goal, performance_target, or working_only_unknown. If the task names a required file, command invocation, compiler/runtime version, URL, SSH/RPC endpoint, branch-to-path mapping, stdout behavior, or service readiness condition, capture that final check as delivery_contract even when creating, configuring, compiling, or validating it must wait for working.\n' +
  'When the task is a bounded edit or cleanup task, capture the allowed edit boundary as delivery_contract too. If the task implies "change only these files", "leave unrelated files untouched", or "leave no extra generated artifacts", keep that boundary in the handoff as part of the final contract instead of treating it as optional cleanup.\n' +
  'If source_of_truth contains a negative boundary such as "do not modify unrelated files", "do not rewrite unaffected regions", "do not change branch state outside the target", or "leave no stray artifacts", carry that negative boundary explicitly in description instead of burying it only in handoff prose.\n' +
  'Do not replace a task-bounded cleanup scope with a broader cleanup inventory just because broader suspicious patterns were discovered during inspection. Extra suspected scope may be mentioned as risk or candidate investigation, but it is not automatically part of the contract.\n' +
  'If part of the acceptance surface is still unknown because the task may depend on hidden verifier expectations, hidden reference outputs, or unobserved boundary checks, preserve that uncertainty as a risk or unknown. Do not treat "not directly visible" as "not required".\n' +
  'Classification test: if a requirement can be checked after final delivery without knowing how it was implemented, classify that requirement as delivery_contract. The commands, edits, installation, service setup, or validation steps used to make it true are working_only_unknown.\n' +
  'Use type exploration_goal for flexible implementation goals where the approach can change.\n' +
  'Use type performance_target for measurable outcomes that require iteration or observation.\n' +
  'Use type working_only_unknown for questions that need execution, mutation, validation, runtime observation, environment setup, dependency installation, generated scaffolding, service startup, data inference, model fitting, sampling, or repeated tuning. Do not keep probing these in inspection once the phase policy blocks them; transfer them clearly to working. Setup and startup work are not their own goal type: if they are part of the externally observed final behavior, capture that behavior as delivery_contract; otherwise describe the unresolved setup or startup need as working_only_unknown or in handoff.risks. When deliverable file contents must be learned or generated from data, keep the file contract separate from the unknown learning or generation work.\n\n' +
  'For tasks whose solution requires deep derivation, runtime experiments, strategy search, iterative validation, or large uncertain reasoning, do not spend inspection trying to complete the derivation. Stop once the delivery contract, verification conditions, known facts, unresolved risks, and first working-phase experiments are clear. Examples include cryptanalysis, exploit design, polyglot construction, algorithm synthesis, statistical modeling, performance tuning, reverse engineering, and search/optimization tasks.\n' +
  'If more thinking would mainly generate candidate solutions rather than confirm authoritative facts, constraints, or validation conditions, stop using tools and output the final handoff draft. Preserve the final contract as delivery_contract, record flexible solution routes as exploration_goal, and hand execution, experiments, tuning, and validation to working.\n\n' +
  'Separate hard constraints from tentative strategy. Do not present a guessed implementation path, algorithm, parameter value, exploit technique, or runtime workaround as a delivery_contract unless the task makes it mandatory.\n' +
  'Do not broaden the authoritative scope. If the task points to specific files, datasets, inputs, or interfaces, keep that scope exact instead of inventing a general scan or extra deliverable.\n' +
  'When blocked, budget-limited, or uncertain, still output one complete handoff draft for intent and subgoals. Do not continue asking for more exploration, do not output the schema, and do not output multiple alternative drafts.\n\n' +
  'In name, use a short stable label such as api-contract, implement-parser, or validation-run.\n' +
  'In description, state the goal or constraint using task-required facts and confirmed evidence. Preserve final acceptance constraints and boundary constraints, but do not use description to claim that a candidate route is already proven or mandatory. If a sentence would read like a chosen recipe, exploit, algorithm, parser strategy, compiler trick, framework choice, or workaround, move it out of description.\n' +
  'In relevant_files, list known paths or use an empty list.\n' +
  'In handoff.confirmed, list only established facts from source_of_truth or confirmed read-only evidence, including confirmed edit-boundary facts when they exist. In handoff.candidates, list only tentative routes or recipes that working may try, without widening the permitted scope. In handoff.risks, list unresolved blockers, missing evidence, or scope risks, including any risk that a broader change could violate the task boundary. Keep these three lists separate.';
