export const inspectionPrompt =
  'Inspect the task and environment before making changes.\n\n' +
  'Original task:\n{{input.question}}\n\n' +
  "Your goal in this phase is to build the handoff model for working, not to solve or implement the task. Use available read-only tools to understand what needs to be delivered, what files or commands matter, and what constraints are visible. Keep a running checklist for the final handoff draft: intent, subgoals, and each subgoal item's name, type, description, relevant_files, and handoff_note. Stop using tools once this checklist is sufficient for working to preserve, do, test, or investigate the right things.\n\n" +
  'Do not edit files, run mutation commands, or implement the solution in this phase.\n\n' +
  'The final handoff draft must use field labels and meanings that match the extraction schema. A later schema extraction step will convert the draft into strict JSON, so make the draft easy to map directly and do not invent extra field names.\n\n' +
  'In intent, write a short stable statement of the task goal. Do not include commands, validation steps, or implementation detail in intent.\n\n' +
  'In subgoals, write a short list of structured handoff items anchored to authoritative task facts and confirmed read-only evidence. Do not broaden the task scope. Before writing subgoals, identify the authoritative facts from the original task and confirmed read-only evidence. Organize subgoals around those facts; do not replace them with a broader, safer, or more generic version of the task. Each item must include name, type, description, relevant_files, and handoff_note.\n\n' +
  'A subgoal is a typed goal, constraint, target, or unknown; it is not an execution step or action list. Do not classify subgoals by what command the next phase might run. Classify them by the role they play in the handoff model: final contract, flexible exploration goal, measurable target, or working-only unknown.\n\n' +
  'Use type delivery_contract for hard requirements such as paths, ports, APIs, output formats, service names, or verifier-facing files.\n' +
  'For delivery_contract, preserve immutable verifier-facing details exactly: literal paths, hostnames, ports, RPC or API names, CLI arguments, output files, schema fields, known contaminated scope, placeholder rules, service lifetime, background process expectations, observable behavior, numeric representation, units, precision, and required call ordering. Behavioral protocols are contracts too: argument meanings, call sequence, persistence, waiting, side effects, and error-visible output belong here when tests observe them. If a verifier-facing file must be produced but its contents depend on data inference, training, optimization, sampling, cracking, search, or runtime experiments, keep only the file path, format, schema, row count, and acceptance surface as delivery_contract; classify the content-generation objective as exploration_goal, performance_target, or working_only_unknown.\n' +
  'Use type exploration_goal for flexible implementation goals where the approach can change.\n' +
  'Use type performance_target for measurable outcomes that require iteration or observation.\n' +
  'Use type working_only_unknown for questions that need execution, mutation, validation, runtime observation, environment setup, dependency installation, generated scaffolding, service startup, data inference, model fitting, sampling, or repeated tuning. Do not keep probing these in inspection once the phase policy blocks them; transfer them clearly to working. Setup and startup work are not their own goal type: if they are part of the externally observed final behavior, capture that behavior as delivery_contract; otherwise describe the unresolved setup or startup need as working_only_unknown or in handoff_note. When deliverable file contents must be learned or generated from data, keep the file contract separate from the unknown learning or generation work.\n\n' +
  'For tasks whose solution requires deep derivation, runtime experiments, strategy search, iterative validation, or large uncertain reasoning, do not spend inspection trying to complete the derivation. Stop once the delivery contract, verification conditions, known facts, unresolved risks, and first working-phase experiments are clear. Examples include cryptanalysis, exploit design, polyglot construction, algorithm synthesis, statistical modeling, performance tuning, reverse engineering, and search/optimization tasks.\n' +
  'If more thinking would mainly generate candidate solutions rather than confirm authoritative facts, constraints, or validation conditions, stop using tools and output the final handoff draft. Preserve the final contract as delivery_contract, record flexible solution routes as exploration_goal, and hand execution, experiments, tuning, and validation to working.\n\n' +
  'Separate hard constraints from tentative strategy. Do not present a guessed implementation path, algorithm, parameter value, or exploit technique as a delivery_contract unless the task makes it mandatory.\n' +
  'Do not broaden the authoritative scope. If the task points to specific files, datasets, inputs, or interfaces, keep that scope exact instead of inventing a general scan or extra deliverable.\n' +
  'When blocked, budget-limited, or uncertain, still output one complete handoff draft for intent and subgoals. Do not continue asking for more exploration, do not output the schema, and do not output multiple alternative drafts.\n\n' +
  'In name, use a short stable label such as api-contract, implement-parser, or validation-run.\n' +
  'In description, state the goal or constraint. In relevant_files, list known paths or use an empty list. In handoff_note, distinguish confirmed facts from unresolved risks, then say what working should preserve, do, test, or investigate.';
