export const verificationPrompt =
  'Verify the result from the working phase and decide whether to accept it or send it back.\n\n' +
  '<source_of_truth>\n{{input.question}}\n</source_of_truth>\n\n' +
  '<inspection_handoff>\n' +
  'Intent:\n{{inspection.intent}}\n\n' +
  'Subgoals:\n{{inspection.subgoals}}\n\n' +
  '</inspection_handoff>\n\n' +
  '<working_result>\n{{working.summary}}\n</working_result>\n\n' +
  '<working_closure_state>\n{{working.closure_state}}\n</working_closure_state>\n\n' +
  'Use inspection and validation tools as needed. Do not do the main implementation work here.\n\n' +
  'source_of_truth is the only acceptance authority. inspection_handoff is fallible and must be checked against source_of_truth before use. Use delivery_contract subgoals as candidate checks, but do not let a contract block acceptance if it conflicts with source_of_truth or adds an extra requirement.\n\n' +
  'A locally successful result is still wrong if it solved a narrowed, renamed, broadened, or otherwise drifted version of the task. Before accepting, check whether the final state still matches the original task boundaries for scope, deliverables, paths, filenames, interfaces, behavioral requirements, and no-unrelated-change constraints.\n\n' +
  "working_closure_state is working's own view of the current strongest progress, the main live blocker, and results that should not be lost. Use it as context, not as acceptance authority: preserve what verification confirms, correct what working overstated, and focus the closing judgment on the true remaining blocker.\n\n" +
  'For each delivery_contract candidate, emit one check with contract, status, and note. Use status "satisfied" only when source_of_truth requires the contract and direct observed evidence shows it is met. Use "unsatisfied" when source_of_truth requires it and evidence shows it is not satisfied. Use "unknown" when source_of_truth requires it but verification lacks enough direct evidence. Use "not_required" when inspection_handoff proposed a contract that source_of_truth does not require.\n\n' +
  'Judge with latest direct evidence, not stale failure memory. If an earlier failure was later repaired or contradicted by stronger direct evidence, treat that earlier failure as superseded and do not let it block accept. Only current active gaps should keep a check unsatisfied or unknown.\n\n' +
  'Checks must cover the full required contract, not just the easiest success condition. If source_of_truth defines a bounded edit, cleanup-only change, repository-state constraint, or clean deliverable requirement, include checks for unrelated file changes, stray generated artifacts, or other boundary conditions when they are part of the task. If that boundary was not directly checked, do not mark the overall requirement satisfied.\n\n' +
  'If working appears to satisfy only a narrowed taxonomy, partial dataset scope, renamed output contract, or guessed hidden-reference interpretation, do not accept that as equivalent to the original task. Keep the relevant check unsatisfied or unknown unless direct evidence shows the original contract itself is met.\n\n' +
  'If multiple plausible interpretations of source_of_truth still lead to different final answers or different cleanup scope, do not mark the relevant check satisfied until source_of_truth or direct observed evidence resolves that ambiguity. A preferred interpretation, partial scan, or broader cleanup inventory is not acceptance authority by itself.\n\n' +
  'If working fixed extra suspicious material outside the original bounded scope, do not automatically treat that broader cleanup as satisfying the task. Unless source_of_truth itself requires the broader cleanup, acceptance must still be judged against the original bounded contract and its no-unrelated-change boundary.\n\n' +
  'In note, distinguish observed evidence from inferred reasoning. If the strongest support is only an inference, a silent zero exit code, file presence alone, partial output, or an unverified candidate route, do not mark the check satisfied. If the task may have violated a no-unrelated-change boundary and verification did not directly rule that out, use unsatisfied or unknown rather than satisfied.\n\n' +
  'When decision is accept, make sure no check is being held open only because it failed earlier in the run. When decision is needs_work, make sure the blocking reason is a current active gap rather than a superseded one.\n\n' +
  'If decision is needs_work, also emit feedback with: preserve for results that still hold and must be kept, blocking_gap for the single most important reason accept is not yet earned, and evidence_needed for the direct evidence or decisive check still required. feedback is a latest-pass closure-failure handoff, not a next-step action plan.\n\n' +
  'Treat exploration_goal, performance_target, and working_only_unknown items as context for what working tried, not as acceptance gates. Return "accept" only when every source_of_truth delivery requirement is satisfied, including required boundary checks; not_required checks may still accept. Return "needs_work" if any source_of_truth delivery requirement is unsatisfied or unknown.';
